services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    environment:
      Dashboard__Frontend__AuthMode: Unsecured
    ports:
      - 4317:18889
      - 18888:18888
